### ISSUE TITLE
deepspeed batch size setting

### ISSUE THREAD

**Issue by TaciturnMute** [TianHongZXY/CoRe#2]
你好。按照你的修改，将strategy修改为deepspeed之后，合理的batch size（例如2）不会出现oom问题。但代码默认配置和论文中的设置似乎对不上？论文里训练generator，batch size设为16，使用了8张A100，但是默认配置是1张GPU，32batch size。可否详细说一下batch size的配置问题？

**Comment by TianHongZXY** [comment]
你好，我训练时每张卡上batch size为2，使用了8张A100，因此batch size为16

**Comment by TianHongZXY** [comment]
你好，我训练generator时每张卡上batch size为2，使用了8张卡，因此batch size为16

**Comment by TaciturnMute** [comment]
那么，代码里默认设置能对上吗？我的理解是没有对上？应该设置micro_batch_size为2，num gpu为8？

**Comment by TianHongZXY** [comment]
代码里默认设置是尝试训练gpt2-large时设置的，上传至github时没有完全恢复成训练gpt-j的配置，对于超参数的设置请参考原论文，谢谢

**Comment by TaciturnMute** [comment]
感谢>.<

**Comment by TaciturnMute** [comment]
你好，还有关于verifier的batch size需要请教。请问step的batch size如何设置？path的batch size为128，是ddp策略下，8卡总共的样本量吗？

**Comment by TianHongZXY** [comment]
是的，8卡总共样本量为128
对于step-level verifier，可以通过调整accumulate_grad_batches实现每128个样本做一次梯度下降

**Comment by TaciturnMute** [comment]
你好，我复现了你的generator针对gsm8k的第0轮的训练。论文里greedy decoding结果为29%，可是我复现的结果没有达到你的效果。我的训练和推断的参数是这样设置的：
目前我训练generator的配置：
epoch 2
gpu 8
gradient_clip_val 1.0
strategy deepspeed_stage_2
num_workers 32
micro_batch_size 16
val_batch_size 16
test_batch_size 16
lr epoch1 le-5 epoch2 1e-6
lr scheduler linear
warm up 0.1
model_name EleutherAI/gpt-j-6B
model type gpt

目前我生成response的配置：
batch size1
do_sample true
top_k 0
top_p 0.75
max_gen_length 512
temperature 0.1

请问我有什么不对的地方吗？

**Comment by TaciturnMute** [comment]
我的结果是15%左右。数据集划分是按照论文来的。
