### ISSUE TITLE
self-thinking部分请教

### ISSUE THREAD

**Issue by aaronlyt** [TianHongZXY/CoRe#3]
你好，有两个问题想请教下，谢谢:
1. 请问能提供self-thinking部分的代码么
2. 在self-thinking训练过程中, step 2使用的questions是和step 1一样的么

**Comment by TianHongZXY** [comment]
你好，
1. self-thinking是用mcts结合generator与verifiers采样更多的samples用于训练，采样的方法是使用`mcts.slurm`进行生成。
2. 使用的question是一样的，只是采样出的solutions会不同。

**Comment by aaronlyt** [comment]
好的，谢谢
